export const MOCK_RECIPES = [
  {
    id: 716429,
    title: "Pasta with Garlic, Tomatoes, Olives & Feta",
    cuisine: "Italian",
    dishTypes: ["pasta", "dinner"],
    readyInMinutes: 45,
    servings: 4,
    image: "https://images.spoonacular.com/recipes/716429-556x370.jpg",
    summary: "A delicious Mediterranean pasta dish with juicy tomatoes, garlic, kalamata olives, and crumbled feta cheese.",
    extendedIngredients: [
      { id: 1, original: "8 oz pasta (spaghetti or penne)", name: "pasta" },
      { id: 2, original: "2 tbsp extra virgin olive oil", name: "olive oil" },
      { id: 3, original: "4 cloves garlic, minced", name: "garlic" },
      { id: 4, original: "2 cups cherry tomatoes, halved", name: "cherry tomatoes" },
      { id: 5, original: "1/2 cup kalamata olives, pitted", name: "olives" },
      { id: 6, original: "1/2 cup feta cheese, crumbled", name: "feta cheese" },
      { id: 7, original: "Fresh basil leaves for garnish", name: "basil" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Bring a large pot of salted water to a boil and cook pasta according to package instructions." },
          { step: "Heat olive oil in a large skillet over medium heat. Add minced garlic and cook for 1 minute until fragrant." },
          { step: "Add cherry tomatoes and olives to the skillet. Sauté for 5-7 minutes until tomatoes begin to soften." },
          { step: "Toss the drained pasta into the skillet with the tomato mixture. Stir well to combine." },
          { step: "Remove from heat, top with crumbled feta cheese and fresh basil, and serve warm." },
        ],
      },
    ],
    tags: ["Vegetarian"],
  },
  {
    id: 644387,
    title: "Garlic Rosemary Roasted Chicken Thighs",
    cuisine: "American",
    dishTypes: ["chicken", "dinner"],
    readyInMinutes: 45,
    servings: 4,
    image: "https://images.unsplash.com/photo-1670398564097-0762e1b30b3a?w=600&h=400&fit=crop&auto=format",
    summary: "Crispy-skinned chicken thighs roasted with rosemary, garlic, and smoked paprika until golden brown.",
    extendedIngredients: [
      { id: 1, original: "4 bone-in, skin-on chicken thighs", name: "chicken thighs" },
      { id: 2, original: "3 cloves garlic, minced", name: "garlic" },
      { id: 3, original: "2 tbsp olive oil", name: "olive oil" },
      { id: 4, original: "1 tbsp fresh rosemary, chopped", name: "rosemary" },
      { id: 5, original: "1 tsp smoked paprika", name: "paprika" },
      { id: 6, original: "Salt and black pepper to taste", name: "salt and pepper" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Preheat oven to 425°F (220°C)." },
          { step: "Pat chicken thighs dry with paper towels." },
          { step: "Mix olive oil, garlic, rosemary, paprika, salt, and pepper in a small bowl." },
          { step: "Rub seasoning mixture all over chicken thighs." },
          { step: "Place skin-side up in a baking dish and roast for 35-40 minutes until golden and internal temp reaches 165°F." },
        ],
      },
    ],
    tags: ["Gluten-Free", "High Protein"],
  },
  {
    id: 715497,
    title: "Berry Acai Smoothie Bowl",
    cuisine: "American",
    dishTypes: ["breakfast", "healthy"],
    readyInMinutes: 15,
    servings: 2,
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&h=400&fit=crop&auto=format",
    summary: "A refreshing smoothie bowl blended with acai, frozen berries, and banana, topped with granola and chia seeds.",
    extendedIngredients: [
      { id: 1, original: "1 packet frozen acai puree", name: "acai" },
      { id: 2, original: "1 cup frozen mixed berries", name: "mixed berries" },
      { id: 3, original: "1 frozen banana", name: "banana" },
      { id: 4, original: "1/2 cup almond milk", name: "almond milk" },
      { id: 5, original: "1/4 cup granola for topping", name: "granola" },
      { id: 6, original: "1 tbsp chia seeds", name: "chia seeds" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Add acai, frozen berries, banana, and almond milk to a high-speed blender." },
          { step: "Blend on high until smooth and thick." },
          { step: "Pour into bowls and top with granola, fresh berries, and chia seeds." },
        ],
      },
    ],
    tags: ["Vegan", "Vegetarian", "Gluten-Free"],
  },
  {
    id: 633344,
    title: "Asian Teriyaki Salmon Bowl",
    cuisine: "Asian",
    dishTypes: ["asian", "dinner"],
    readyInMinutes: 30,
    servings: 2,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop&auto=format",
    summary: "Pan-seared salmon coated in a sweet and savory teriyaki glaze, served over jasmine rice and steamed edamame.",
    extendedIngredients: [
      { id: 1, original: "2 salmon fillets (6 oz each)", name: "salmon" },
      { id: 2, original: "3 tbsp teriyaki sauce", name: "teriyaki sauce" },
      { id: 3, original: "1 cup cooked jasmine rice", name: "jasmine rice" },
      { id: 4, original: "1/2 cup shelled edamame", name: "edamame" },
      { id: 5, original: "1 tsp sesame seeds", name: "sesame seeds" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Season salmon fillets light with salt and pepper." },
          { step: "Heat a non-stick skillet over medium-high heat with 1 tsp oil." },
          { step: "Sear salmon skin-side down for 4 minutes, flip, and pour teriyaki sauce over." },
          { step: "Cook for another 3 minutes until glazed and cooked through." },
          { step: "Serve over rice with edamame and garnish with sesame seeds." },
        ],
      },
    ],
    tags: ["High Protein"],
  },
  {
    id: 654959,
    title: "Fresh Vegetable Pasta Primavera",
    cuisine: "Italian",
    dishTypes: ["pasta", "healthy"],
    readyInMinutes: 25,
    servings: 4,
    image: "https://images.spoonacular.com/recipes/654959-556x370.jpg",
    summary: "Linguine tossed with sauteed zucchini, bell peppers, cherry tomatoes, parmesan, and fresh herbs.",
    extendedIngredients: [
      { id: 1, original: "12 oz linguine pasta", name: "linguine" },
      { id: 2, original: "1 zucchini, sliced", name: "zucchini" },
      { id: 3, original: "1 red bell pepper, sliced", name: "bell pepper" },
      { id: 4, original: "2 tbsp butter", name: "butter" },
      { id: 5, original: "1/2 cup grated parmesan cheese", name: "parmesan" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Cook linguine in salted boiling water until al dente." },
          { step: "Sauté vegetables in butter until tender-crisp." },
          { step: "Toss pasta with vegetables, parmesan, and pasta water until creamy." },
        ],
      },
    ],
    tags: ["Vegetarian"],
  },
  {
    id: 640352,
    title: "Classic Chocolate Lava Cake",
    cuisine: "Dessert",
    dishTypes: ["dessert"],
    readyInMinutes: 25,
    servings: 2,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop&auto=format",
    summary: "Rich chocolate cakes with warm molten centers, served warm with powdered sugar and berries.",
    extendedIngredients: [
      { id: 1, original: "4 oz dark chocolate, chopped", name: "dark chocolate" },
      { id: 2, original: "1/2 cup butter", name: "butter" },
      { id: 3, original: "2 eggs + 2 egg yolks", name: "eggs" },
      { id: 4, original: "1/4 cup sugar", name: "sugar" },
      { id: 5, original: "2 tbsp flour", name: "flour" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Preheat oven to 425°F and butter ramekins." },
          { step: "Melt chocolate and butter together." },
          { step: "Whisk eggs and sugar, fold into chocolate, then stir in flour." },
          { step: "Bake 12 minutes until edges are firm but center is soft." },
        ],
      },
    ],
    tags: ["Vegetarian"],
  },
  {
    id: 715769,
    title: "Creamy Thai Green Curry with Vegetables",
    cuisine: "Asian",
    dishTypes: ["asian", "healthy"],
    readyInMinutes: 35,
    servings: 4,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop&auto=format",
    summary: "A fragrant Thai curry cooked with coconut milk, green curry paste, bamboo shoots, and fresh basil.",
    extendedIngredients: [
      { id: 1, original: "1 can (14 oz) coconut milk", name: "coconut milk" },
      { id: 2, original: "2 tbsp Thai green curry paste", name: "green curry paste" },
      { id: 3, original: "1 cup tofu or chicken, cubed", name: "tofu" },
      { id: 4, original: "1 cup mixed vegetables (bamboo shoots, bell peppers)", name: "vegetables" },
      { id: 5, original: "Fresh Thai basil leaves", name: "thai basil" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Simmer green curry paste in 1/2 cup coconut milk until fragrant." },
          { step: "Add remaining coconut milk, protein, and vegetables." },
          { step: "Simmer for 15 minutes until vegetables are tender." },
          { step: "Stir in Thai basil before serving with jasmine rice." },
        ],
      },
    ],
    tags: ["Vegan", "Vegetarian", "Gluten-Free"],
  },
  {
    id: 655219,
    title: "Peanut Butter Banana Breakfast Oatmeal",
    cuisine: "American",
    dishTypes: ["breakfast", "healthy"],
    readyInMinutes: 10,
    servings: 1,
    image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&h=400&fit=crop&auto=format",
    summary: "Warm rolled oats cooked with milk, swirled with creamy peanut butter and topped with sliced banana.",
    extendedIngredients: [
      { id: 1, original: "1/2 cup rolled oats", name: "rolled oats" },
      { id: 2, original: "1 cup milk or oat milk", name: "milk" },
      { id: 3, original: "2 tbsp natural peanut butter", name: "peanut butter" },
      { id: 4, original: "1 banana, sliced", name: "banana" },
      { id: 5, original: "1 tbsp honey or maple syrup", name: "honey" },
    ],
    analyzedInstructions: [
      {
        steps: [
          { step: "Combine oats and milk in a small saucepan." },
          { step: "Bring to a gentle boil, reduce heat, and cook 5 minutes." },
          { step: "Stir in peanut butter and sweetener." },
          { step: "Top with sliced banana and serve." },
        ],
      },
    ],
    tags: ["Vegetarian", "High Protein"],
  },
];
